TOOL_REGISTRY = {
    "GENERAL_CHAT": "GENERAL_CHAT",
    "BOOK_APPOINTMENT": "BOOK_APPOINTMENT",
    "CANCEL_APPOINTMENT": "CANCEL_APPOINTMENT",
    "CHECK_QUEUE": "CHECK_QUEUE",
    "DOCTOR_DASHBOARD": "DOCTOR_DASHBOARD",
    "PATIENT_DASHBOARD": "PATIENT_DASHBOARD",
}